export const currentUser = {
  id: "user_001",
  email: "alex@devstash.io",
  name: "Alex Chen",
  avatarUrl: null,
  isPro: true,
  createdAt: "2025-01-15T08:00:00Z",
  updatedAt: "2026-05-10T14:30:00Z",
};

export const itemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "Code", color: "#3b82f6", isSystem: true, userId: null },
  { id: "type_prompt", name: "Prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true, userId: null },
  { id: "type_note", name: "Note", icon: "FileText", color: "#10b981", isSystem: true, userId: null },
  { id: "type_command", name: "Command", icon: "Terminal", color: "#f59e0b", isSystem: true, userId: null },
  { id: "type_file", name: "File", icon: "Folder", color: "#6b7280", isSystem: true, userId: null },
  { id: "type_image", name: "Image", icon: "Image", color: "#ec4899", isSystem: true, userId: null },
  { id: "type_url", name: "URL", icon: "Link", color: "#06b6d4", isSystem: true, userId: null },
];

export const collections = [
  {
    id: "col_react",
    name: "React Patterns",
    description: "Reusable React component patterns and hooks",
    isFavorite: true,
    userId: "user_001",
    createdAt: "2025-03-10T10:00:00Z",
    updatedAt: "2026-05-12T09:00:00Z",
  },
  {
    id: "col_python",
    name: "Python Snippets",
    description: "Handy Python utilities and scripts",
    isFavorite: false,
    userId: "user_001",
    createdAt: "2025-04-22T16:00:00Z",
    updatedAt: "2026-04-28T11:00:00Z",
  },
  {
    id: "col_prompts",
    name: "AI Prompts",
    description: "Curated prompts for coding and debugging",
    isFavorite: true,
    userId: "user_001",
    createdAt: "2025-02-05T12:00:00Z",
    updatedAt: "2026-05-14T08:00:00Z",
  },
  {
    id: "col_commands",
    name: "Terminal Commands",
    description: "Useful CLI one-liners and scripts",
    isFavorite: false,
    userId: "user_001",
    createdAt: "2025-11-18T20:00:00Z",
    updatedAt: "2026-05-01T15:00:00Z",
  },
];

export const items = [
  {
    id: "item_001",
    title: "useDebounce hook",
    contentType: "text",
    content: "import { useState, useEffect } from 'react';\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState<T>(value);\n\n  useEffect(() => {\n    const handler = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(handler);\n  }, [value, delay]);\n\n  return debouncedValue;\n}",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "A custom React hook that debounces a value by a specified delay.",
    isFavorite: true,
    isPinned: false,
    language: "typescript",
    userId: "user_001",
    typeId: "type_snippet",
    collectionId: "col_react",
    tags: ["hooks", "typescript", "performance"],
    createdAt: "2025-06-12T09:00:00Z",
    updatedAt: "2026-04-20T14:00:00Z",
  },
  {
    id: "item_002",
    title: "Explain this function and suggest improvements",
    contentType: "text",
    content: "Paste a function and I'll explain what it does, identify potential bugs, and suggest improvements for readability and performance.",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "AI prompt for code review and improvement suggestions.",
    isFavorite: true,
    isPinned: false,
    language: null,
    userId: "user_001",
    typeId: "type_prompt",
    collectionId: "col_prompts",
    tags: ["ai", "code-review", "prompt"],
    createdAt: "2025-07-20T11:00:00Z",
    updatedAt: "2026-03-15T16:00:00Z",
  },
  {
    id: "item_003",
    title: "Next.js 16 migration notes",
    contentType: "text",
    content: "## Breaking Changes in Next.js 16\n\n- Middleware now runs on Edge runtime by default\n- `appDir` is the only supported directory structure\n- `next/head` removed — use Metadata API\n- Route handlers use standard Web APIs\n- `next/font` is now the default font system",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Key points from the Next.js 16 migration guide.",
    isFavorite: false,
    isPinned: false,
    language: "markdown",
    userId: "user_001",
    typeId: "type_note",
    collectionId: null,
    tags: ["nextjs", "migration", "reference"],
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-01-10T08:00:00Z",
  },
  {
    id: "item_004",
    title: "Find large files recursively",
    contentType: "text",
    content: "find / -type f -size +100M -exec ls -lh {} \\; 2>/dev/null | sort -k5 -h",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Lists all files larger than 100MB recursively, sorted by size.",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    userId: "user_001",
    typeId: "type_command",
    collectionId: "col_commands",
    tags: ["linux", "disk-usage", "cli"],
    createdAt: "2025-08-14T15:00:00Z",
    updatedAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "item_005",
    title: "Tailwind CSS v4 cheat sheet",
    contentType: "text",
    content: "## Tailwind v4 Changes\n\n- CSS-first config: use `@import \"tailwindcss\"`\n- No `tailwind.config.*` file\n- `@theme` directive for design tokens\n- Container queries built-in\n- Dynamic utility values with `--value()`",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Quick reference for Tailwind CSS v4 differences.",
    isFavorite: false,
    isPinned: true,
    language: "markdown",
    userId: "user_001",
    typeId: "type_note",
    collectionId: null,
    tags: ["tailwind", "css", "reference"],
    createdAt: "2026-04-05T12:00:00Z",
    updatedAt: "2026-05-10T09:00:00Z",
  },
  {
    id: "item_006",
    title: "Generate a REST API endpoint with validation",
    contentType: "text",
    content: "Create a TypeScript REST API endpoint using Next.js route handlers with Zod validation, proper error handling, and TypeScript types for request/response.",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "AI prompt for scaffolding API routes with validation.",
    isFavorite: true,
    isPinned: false,
    language: null,
    userId: "user_001",
    typeId: "type_prompt",
    collectionId: "col_prompts",
    tags: ["ai", "api", "typescript", "nextjs"],
    createdAt: "2026-02-18T14:00:00Z",
    updatedAt: "2026-04-30T11:00:00Z",
  },
  {
    id: "item_007",
    title: "Python list flatten un-nest",
    contentType: "text",
    content: "def flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Recursively flattens a nested list of arbitrary depth.",
    isFavorite: false,
    isPinned: false,
    language: "python",
    userId: "user_001",
    typeId: "type_snippet",
    collectionId: "col_python",
    tags: ["python", "recursion", "utilities"],
    createdAt: "2025-09-08T10:00:00Z",
    updatedAt: "2026-03-22T17:00:00Z",
  },
  {
    id: "item_008",
    title: "Storybook setup guide",
    contentType: "url",
    content: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: "https://storybook.js.org/docs/react/get-started",
    description: "Official Storybook documentation for React project setup.",
    isFavorite: false,
    isPinned: false,
    language: null,
    userId: "user_001",
    typeId: "type_url",
    collectionId: null,
    tags: ["storybook", "docs", "reference"],
    createdAt: "2026-04-12T13:00:00Z",
    updatedAt: "2026-04-12T13:00:00Z",
  },
  {
    id: "item_009",
    title: "Prisma reset and reseed",
    contentType: "text",
    content: "npx prisma db push --force-reset && npx prisma db seed",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Quick command to reset the database and re-run seeds.",
    isFavorite: true,
    isPinned: false,
    language: "bash",
    userId: "user_001",
    typeId: "type_command",
    collectionId: "col_commands",
    tags: ["prisma", "database", "cli"],
    createdAt: "2025-10-30T09:00:00Z",
    updatedAt: "2026-04-15T08:00:00Z",
  },
  {
    id: "item_010",
    title: "Zustand store pattern",
    contentType: "text",
    content: "import { create } from 'zustand';\n\ninterface CounterStore {\n  count: number;\n  increment: () => void;\n  decrement: () => void;\n  reset: () => void;\n}\n\nexport const useCounterStore = create<CounterStore>((set) => ({\n  count: 0,\n  increment: () => set((state) => ({ count: state.count + 1 })),\n  decrement: () => set((state) => ({ count: state.count - 1 })),\n  reset: () => set({ count: 0 }),\n}));",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    description: "Minimal Zustand store boilerplate with TypeScript.",
    isFavorite: false,
    isPinned: false,
    language: "typescript",
    userId: "user_001",
    typeId: "type_snippet",
    collectionId: "col_react",
    tags: ["zustand", "state-management", "typescript"],
    createdAt: "2026-03-01T11:00:00Z",
    updatedAt: "2026-05-05T16:00:00Z",
  },
];
